### ISSUE TITLE
Windows Traceroute timeout.

### ISSUE THREAD

**Issue by alexsotocx** [stephenwvickers/node-net-ping#11]
Hello i have been trying the module in linux, os x and windows and it works great... but in windows the ping works, the traceroute works but it just give a timeout in each hop except in the last one.
Here is the output
![capture](https://cloud.githubusercontent.com/assets/6225534/11969729/f2f624e4-a8eb-11e5-8d09-a7013cf2343f.PNG)

**Comment by alexsotocx** [comment]
I executed the trace route command directly from windows and it works

**Comment by stephenwvickers** [comment]
Hi,

Can you confirm if this is a local address?

Also, can you please provide a packet trace of the outgoing and incoming packets?

Thanks

Steve

**Comment by alexsotocx** [comment]
Not it's not a local address. Is the output of the DNS of eventtia.com ( I ran the same command in my Mac and it works like a charm) 

The other thing... How can I provide you that data?   Wireshark?

**Comment by stephenwvickers** [comment]
You can use Wireshark to provide the data.

**Comment by alexsotocx** [comment]
Hello I attach the files you are asking for.

I ran the commands 
node trace-route.js 20 50.56.49.58 (Request time out)
node ping-response-time.js 50.56.49.58 (Works)
[wireshark windows caputre.zip](https://github.com/stephenwvickers/node-net-ping/files/77848/wireshark.windows.caputre.zip)

**Comment by stephenwvickers** [comment]
Looking at the packet trace I do indeed see ICMP time exceeded messages, which should be passed back to you.

If I execute the trace-route command it works for me, I use Windows 7:

```
C:\home\projects\node-net-ping>node example\trace-route.js 20 50.56.49.58
50.56.49.58: 192.168.1.1 (ttl=1 ms=0)
50.56.49.58: RequestTimedOutError: Request timed out (ttl=2 ms=4005)
50.56.49.58: 10.248.28.145 (ttl=3 ms=40)
50.56.49.58: 10.247.84.25 (ttl=4 ms=20)
50.56.49.58: 10.247.84.6 (ttl=5 ms=20)
50.56.49.58: 10.247.84.9 (ttl=6 ms=20)
50.56.49.58: 10.247.84.18 (ttl=7 ms=28)
50.56.49.58: 87.237.20.224 (ttl=8 ms=20)
50.56.49.58: 87.237.20.73 (ttl=9 ms=20)
50.56.49.58: 80.150.170.17 (ttl=10 ms=20)
50.56.49.58: 80.150.170.106 (ttl=11 ms=30)
50.56.49.58: 129.250.5.24 (ttl=12 ms=30)
50.56.49.58: 129.250.2.18 (ttl=13 ms=91)
50.56.49.58: 129.250.3.207 (ttl=14 ms=93)
50.56.49.58: 129.250.2.166 (ttl=15 ms=116)
50.56.49.58: 129.250.2.25 (ttl=16 ms=112)
50.56.49.58: 157.238.64.42 (ttl=17 ms=113)
50.56.49.58: RequestTimedOutError: Request timed out (ttl=18 ms=4002)
50.56.49.58: 50.56.6.163 (ttl=19 ms=133)
50.56.49.58: 184.106.126.129 (ttl=20 ms=114)
50.56.49.58: TimeExceededError: Time exceeded (source=184.106.126.129)
```

Could it be that you have a firewall or some program that prevents the response messages from receiving your program?

Steve

**Comment by stephenwvickers** [comment]
No more information from the user.

**Comment by tkapluk** [comment]
This bug still present.

> request: addressFamily=1 target=8.8.8.8 id=2 buffer=0800bb753c8800020000000000000000
> 8.8.8.8: RequestTimedOutError: Request timed out (ttl=1 ms=4032)
> request: addressFamily=1 target=8.8.8.8 id=3 buffer=0800bb743c8800030000000000000000
> 8.8.8.8: RequestTimedOutError: Request timed out (ttl=2 ms=4005)
> request: addressFamily=1 target=8.8.8.8 id=4 buffer=0800bb733c8800040000000000000000
> 8.8.8.8: RequestTimedOutError: Request timed out (ttl=3 ms=4003)
> 8.8.8.8: Error: Too many timeouts

From wireshark:

![net-ping](https://user-images.githubusercontent.com/25935853/47998381-d2a74b80-e107-11e8-8578-758ac9f1e0ec.jpg)

Windows tracert work fine:

> tracert 8.8.8.8
> 
>   1    11 ms     5 ms    <1 мс  192.168.0.1
>   2     2 ms     2 ms     4 ms  10.9.16.1
>   3    31 ms     1 ms     1 ms  172.16.3.32
>  ....

System:
```
D:\>ver
Microsoft Windows [Version 10.0.17134.345]

D:\>node -v
v10.13.0

D:\>npm -v
6.4.1
```

**Comment by tkapluk** [comment]
Problem in Windows Firewall.
