### ISSUE TITLE
npm install error in OSX

### ISSUE THREAD

**Issue by oriharel** [stephenwvickers/node-net-ping#13]
I get this
CXX(target) Release/obj.target/raw/src/raw.o
../src/raw.cc:662:21: error: expected ';' after expression
                String::Utf8String address (args[3]);
                                  ^
                                  ;
../src/raw.cc:662:11: error: no member named 'Utf8String' in 'v8::String'
                String::Utf8String address (args[3]);

and many more errors.

**Comment by stephenwvickers** [comment]
Hi,

The latest version of raw-socket is only tested with Node.js 0.12.x and onward.

Regards

Steve
