### ISSUE TITLE
raw socket

### ISSUE THREAD

**Issue by sonnyp** [stephenwvickers/node-net-ping#18]
Can you explain what is the rational behind using raw socket for node-net-ping? 

Requiring root privilege on Linux is a pain for my use case but mostly I'm curious about the reason.

Thanks

**Comment by sonnyp** [comment]
okay, got my answer icmp is neiter udp nor tcp

There must be a way to use icmp in node land on Linux without root.
The ping utility doesn't require root privileges.

Where should I start looking at?

Thanks

**Comment by stephenwvickers** [comment]
Hi,

Try "man setcap" and "man capabilities", specifically the "CAP_NET_RAW" capability.

Steve

**Comment by sonnyp** [comment]
@stephenwvickers thanks
