### ISSUE TITLE
When all pings completed ?

### ISSUE THREAD

**Issue by irom77** [stephenwvickers/node-net-ping#19]
Great program Stepen, works perfectly for me. I would like to send output to the stream instead of console, and don't know when to stop sending to the stream. So my question is how do I know net-ping is finished (got all responses and timeouts)

**Comment by stephenwvickers** [comment]
Hi Irek,

Are you referring to the `traceRoute()` method?

Steve

**Comment by irom77** [comment]
No, no sorry. I am using session.pingHost (target, callback)

**Comment by stephenwvickers** [comment]
Ok, I guess you have many pings going on, and want to know when they are all one?

If yes, then you will need to track this using something like:

```javascript
var ping = require("net-ping")
var session = ping.createSession()
var count = 0

function doneCb(error, target, sent, rcvd) {
   count--;

   // Handle results...

   if (count <= 0) {
      // All requests done, so close the stream...
   }
}

var ipsToPing = ["1.2.3.4", "5.6.7.8"]

for (var ip in ipsToPing) {
   count++
   session.pingHost(ip, doneCb)
}
```

Steve

**Comment by stephenwvickers** [comment]
If I misunderstood the question let me know.

**Comment by irom77** [comment]
Thank you Steve, this is what I was looking for. In fact I used similar callback , just put counter in the wrong place..now found it out because of what you posted above
