### ISSUE TITLE
Error: The specified procedure could not be found.

### ISSUE THREAD

**Issue by umutm** [stephenwvickers/node-net-ping#2]
Hi Stephen,

Hope that you are fine. Luckily (or unluckily :)), I'm again the 1st to open an issue regarding net-ping.. this time on GitHub.

The BitBucket repo was removed, so, couldn't find the answer of a pre-replied question.

After installing net-ping, I get the error below while running the .js file:
C:\Users\u\test\node_modules\net-ping\node_modules\raw-socket\build\Release\raw.node

which I had asked the same question on BitBucket and remember that it was a path-related issue. However, couldn't find a solution this time and wanted to re-ask.

Thanks very much.

**Comment by stephenwvickers** [comment]
Hi,

I hope you are keeping well.

This error would suggest to me that the raw.node library was compiled for
one system and ran on another?

Does it give the procedure name?

Steve

**Comment by umutm** [comment]
Hi,

Thanks, all well.

I used to compile it on my Win7 and run on 2012 server which worked fine. Now compiled on Win10 which can be the problem.

The full error is:
module.js:355
  Module._extensions[extension](this, filename);
                               ^

Error: The specified procedure could not be found.
C:\Users\u\test\node_modules\net-ping\node_modules\raw-socket\build\Release\raw.node
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (C:\Users\u\test\node_modules\net-ping\node_modules\net-ping\node_modules\raw-socket\index.js:4:11)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)

I'll try compiling it directly in the server and retry.

**Comment by stephenwvickers** [comment]
I'll wait for your results.

**Comment by umutm** [comment]
Although not sure, I believe that the module is not Node v4-ready or it is an Node v4 and node-gyp related issue.

It all worked fine with Node v0.12.7.

Can the module be installed to v4 on your end?

**Comment by umutm** [comment]
Just saw https://github.com/stephenwvickers/node-net-ping/issues/3 .

Thanks very much and look forward to the update on raw-socket.
