### ISSUE TITLE
No DestinationUnreachableError on centos 6 / redhat 6

### ISSUE THREAD

**Issue by korzhev** [stephenwvickers/node-net-ping#20]
I ping remote server from centos 7 server. If remote server is down, I get several **RequestTimedOutError** and then I get only. **DestinationUnreachableError**, what is absolutly fine for me. But when I try to ping same remote server from centos 6 server, I get only **RequestTimedOutError**. Is there any way to fix return error?

**Comment by stephenwvickers** [comment]
This could be explained by your local firewall configuration for example - i.e. the difference between the two CentOS versions.  Also, your kernel could be triggering a destination unreachable within its routing when it received the first few request timeouts for the IP address being pinged.

**Comment by korzhev** [comment]
Any suggestion
