### ISSUE TITLE
npm install error!!!

### ISSUE THREAD

**Issue by heartblueflower** [stephenwvickers/node-net-ping#21]
./npm install net-ping
-\|/-\|/-\|/-\|/-\-\|/-\|/-\|/--\
> raw-socket@1.4.0 install /home/node-v4.4.3-linux-x64/bin/node_modules/net-ping/node_modules/raw-socket
> node-gyp rebuild

Traceback (most recent call last):
  File "/home/node-v4.4.3-linux-x64/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py", line 16, in <module>
    sys.exit(gyp.script_main())
  File "/home/node-v4.4.3-linux-x64/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 545, in script_main
    return main(sys.argv[1:])
  File "/home/node-v4.4.3-linux-x64/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 538, in main
    return gyp_main(args)
  File "/home/node-v4.4.3-linux-x64/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 514, in gyp_main
    options.duplicate_basename_check)
  File "/home/node-v4.4.3-linux-x64/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 130, in Load
    params['parallel'], params['root_targets'])
  File "/home/node-v4.4.3-linux-x64/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 2775, in Load
    variables, includes, depth, check, True)
  File "/home/node-v4.4.3-linux-x64/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 391, in LoadTargetBuildFile
    includes, True, check)
  File "/home/node-v4.4.3-linux-x64/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 243, in LoadOneBuildFile
    None)
  File "binding.gyp", line 1
    {
     ^
SyntaxError: invalid syntax
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/home/node-v4.4.3-linux-x64/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 2.6.32-431.el6.x86_64
gyp ERR! command "/home/node-v4.4.3-linux-x64/bin/node" "/home/node-v4.4.3-linux-x64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/node-v4.4.3-linux-x64/bin/node_modules/net-ping/node_modules/raw-socket
gyp ERR! node -v v4.4.3
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 
npm ERR! Linux 2.6.32-431.el6.x86_64
npm ERR! argv "/home/node-v4.4.3-linux-x64/bin/node" "/home/node-v4.4.3-linux-x64/bin/npm" "install" "net-ping"
npm ERR! node v4.4.3
npm ERR! npm  v2.15.1
npm ERR! code ELIFECYCLE

npm ERR! raw-socket@1.4.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the raw-socket@1.4.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the raw-socket package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs raw-socket
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls raw-socket
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/node-v4.4.3-linux-x64/bin/npm-debug.log

**Comment by tinnocente** [comment]
same - after upgrading to latest version of Node this module no longer works.

**Comment by stephenwvickers** [comment]
I haven't had time to look into this too much, but a quick test on a MacBook pro doesn't experience the same issue:

```
Stephens-MBP:np5 stephen$ npm install net-ping
\
> raw-socket@1.4.0 install /Users/stephen/Tmp/node_modules/net-ping/node_modules/raw-socket
> node-gyp rebuild

  CXX(target) Release/obj.target/raw/src/raw.o
  SOLINK_MODULE(target) Release/raw.node
net-ping@1.2.0 ../node_modules/net-ping
└── raw-socket@1.4.0 (nan@2.0.9)
Stephens-MBP:np5 stephen$ node -v
v4.4.3
Stephens-MBP:np5 stephen$ npm -v
2.15.1
```

Steve

**Comment by tinnocente** [comment]
Hey Steve, I see you're on node v.4.4.3 whereas I am on 5.10.1

Attached is my debug log.  Hope it helps!

[npm-debug.txt](https://github.com/stephenwvickers/node-net-ping/files/232491/npm-debug.txt)

**Comment by stephenwvickers** [comment]
What version of Python are you using?

**Comment by tinnocente** [comment]
Python 2.6.6 (r266:84292, Dec 26 2010, 22:31:48)

**Comment by tinnocente** [comment]
Hi Stephen, should I try updating Python?

**Comment by stephenwvickers** [comment]
Yes, I would say yes, python 2.7 is recommended by node-gyp and that's what I use.

I have installed successfully with node 5.11.0 using npm 3.8.6 and python 2.7.

**Comment by al095660** [comment]
I have the same problem here, and i have node, npm and python updated (same versions you pointed above). Any thoughts?

<pre>
C:\node\watchbot>npm install net-ping --save

> raw-socket@1.4.0 install C:\node\watchbot\node_modules\raw-socket
> node-gyp rebuild


C:\node\watchbot\node_modules\raw-socket>if not defined npm_config_node_gyp (nod
e "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules
\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
Building the projects in this solution one at a time. To enable parallel build,
please add the "/m" switch.
MSBUILD : error MSB4132: The tools version "2.0" is unrecognized. Available too
ls versions are "4.0".
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe
` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\
npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:100:13)
gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces
s.js:204:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodej
s\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\node\watchbot\node_modules\raw-socket
gyp ERR! node -v v5.11.0
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
npm WARN watchbot@1.0.0 No repository field.
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "net-ping" "--save"
npm ERR! node v5.11.0
npm ERR! npm  v3.8.6
npm ERR! code ELIFECYCLE

npm ERR! raw-socket@1.4.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the raw-socket@1.4.0 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the raw-socket package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs raw-socket
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls raw-socket
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\node\watchbot\npm-debug.log

C:\node\watchbot>
</pre>

**Comment by al095660** [comment]
Solved. As the error message says, MSBUILD was using the wrong tools, so googling it up, i just had to install Microsoft Visual Studio 2013 with C++ redist (you can found it [here](https://www.microsoft.com/en-us/download/details.aspx?id=44914)) and that was it.

Someone can find [this thread](https://github.com/chjj/pty.js/issues/60) very helpful.

Thanks anyway!

**Comment by tinnocente** [comment]
Updated Python: Python 2.7.11 (default, Apr 27 2016, 15:42:44)

Producing the same build error.  Must be something with my environment.  Appreciate any ideas.

[npm-debug (2).txt](https://github.com/stephenwvickers/node-net-ping/files/239303/npm-debug.2.txt)

**Comment by stephenwvickers** [comment]
I would suggest checking out the git repo for raw-socket (this is what is failing to build), and try to build by hand, e.g.:

```
git clone https://github.com/stephenwvickers/node-raw-socket.git
cd node-raw-socket
node-gyp configure
node-gyp build
```

Sometimes I find npm hides build errors, this should reveal them.

**Comment by al095660** [comment]
@tinnocente Try to use the latest version of node and npm. As i can see in the log file, you've installed the node version 5.10.1 and the npm version 3.8.3 (node version 5.11.0 and npm version 3.8.6 are already available). If that fails, try to do what @stephenwvickers says.

**Comment by stephenwvickers** [comment]
I've also found in the past upgrades of the node binary may result in node-gyp build failures where globally installed modules need to be upgraded (I have no data to back this up).

Upgrading the Visual Studio version after installing node may also cause you an issue (passing "--msvs_version=..." at the command prompt can help here).

**Comment by dimonnwc3** [comment]
Problem is in raw-socket dependency. There is ["nan": "2.0.*"](https://github.com/stephenwvickers/node-raw-socket/blob/master/package.json#L10) dependency in package.json, but it's old version don't work in node 6.

I have manually change nan version in raw-sockets dependency to from "nan": "2.0.*" "nan": "2.3.*"
then: _npm i_
and build: _node-gyp configure_
_node-gyp build_

Now we can put working raw-socket in this package and it will work fine.

**Comment by tinnocente** [comment]
@dimonnwc3 brilliant!  that worked.  Should update npm registry with correct version of raw-socket.  Thanks (all) for your help.

**Comment by stephenwvickers** [comment]
Version 1.5.0 of raw-socket has been published to npm

**Comment by stephenwvickers** [comment]
@NimrodGeva confirmed new version of raw-socket resolved the issue in:

https://github.com/stephenwvickers/node-net-ping/issues/24

Also, I see a change has been made in node-gyp to handle windows style line endings.

**Comment by sourabhjha1993** [comment]
net-ping is not working with node.js version 12.18.1. Does anybody has any solution?
