### ISSUE TITLE
Error: Callback was already called. on short timeouts

### ISSUE THREAD

**Issue by j-martyn** [stephenwvickers/node-net-ping#22]
Callback is called second time on [index.js:339](https://github.com/stephenwvickers/node-net-ping/blob/b4c96f136c4995a25db474c9ec8ddb1ce28cb962/index.js#L339) while using `.prototype.pingHost`.
Firts time callback is being called on [index.js:298](https://github.com/stephenwvickers/node-net-ping/blob/b4c96f136c4995a25db474c9ec8ddb1ce28cb962/index.js#L298).
It sometimes reproduces while setting short timeouts for Session, try to set `timeout: 1`

**Comment by stephenwvickers** [comment]
Can you provide a program which emits the issue?

Also, that timeout is 1 milliseconds, which is too short to be useful.

**Comment by stephenwvickers** [comment]
No further information provied.
