### ISSUE TITLE
Failed at the raw-socket@1.4.0 install script 'node-gyp rebuild'

### ISSUE THREAD

**Issue by Dylan1116** [stephenwvickers/node-net-ping#23]
@stephenwvickers 
Looks like I am having an issue on Windows 10 installing net-ping.  It's looking for the Windows SDK version 8.1, having Windows 10 this might be an issue.  It looks to be targeting the Raw Socket.  I attached the full error log. 
[net-pingErrLog.txt](https://github.com/stephenwvickers/node-net-ping/files/257909/net-pingErrLog.txt)

Just in Case:
C:\Dev\PV\src\WebServer>npm install net-ping
npm info it worked if it ends with ok
npm info using npm@2.14.12
npm info using node@v4.3.1
npm info ok
npm info it worked if it ends with ok
npm info using npm@2.14.12
npm info using node@v4.3.1
npm info package.json edge@5.0.0 No license field.
npm info package.json node-schedule@1.0.0 No license field.
npm info package.json passport-local@1.0.0 No license field.
npm info package.json tv4@1.2.7 No license field.
npm info addNameTag [ 'net-ping', 'latest' ]
npm info attempt registry request try #1 at 3:08:32 PM
npm http request GET https://registry.npmjs.org/net-ping
npm http 200 https://registry.npmjs.org/net-ping
npm info retry fetch attempt 1 at 3:08:32 PM
npm info attempt registry request try #1 at 3:08:32 PM
npm http fetch GET https://registry.npmjs.org/net-ping/-/net-ping-1.2.0.tgz
npm http fetch 200 https://registry.npmjs.org/net-ping/-/net-ping-1.2.0.tgz
npm info install net-ping@1.2.0 into C:\Dev\PV\src\WebServer
npm info installOne net-ping@1.2.0
npm info preinstall net-ping@1.2.0
npm info attempt registry request try #1 at 3:08:33 PM
npm http request GET https://registry.npmjs.org/raw-socket
npm http 200 https://registry.npmjs.org/raw-socket
npm info retry fetch attempt 1 at 3:08:33 PM
npm info attempt registry request try #1 at 3:08:33 PM
npm http fetch GET https://registry.npmjs.org/raw-socket/-/raw-socket-1.4.0.tgz
npm http fetch 200 https://registry.npmjs.org/raw-socket/-/raw-socket-1.4.0.tgz
npm info install raw-socket@1.4.0 into C:\Dev\PV\src\WebServer\node_modules\net-ping
npm info installOne raw-socket@1.4.0
npm info preinstall raw-socket@1.4.0
npm info attempt registry request try #1 at 3:08:33 PM
npm http request GET https://registry.npmjs.org/nan
npm http 304 https://registry.npmjs.org/nan
npm info install nan@2.0.9 into C:\Dev\PV\src\WebServer\node_modules\net-ping\node_modules\raw-socket
npm info installOne nan@2.0.9
npm info preinstall nan@2.0.9
npm info build C:\Dev\PV\src\WebServer\node_modules\net-ping\node_modules\raw-socket\node_modules\nan
npm info linkStuff nan@2.0.9
npm info install nan@2.0.9
npm info postinstall nan@2.0.9
npm info build C:\Dev\PV\src\WebServer\node_modules\net-ping\node_modules\raw-socket
npm info linkStuff raw-socket@1.4.0
npm info install raw-socket@1.4.0

> raw-socket@1.4.0 install C:\Dev\PV\src\WebServer\node_modules\net-ping\node_modules\raw-socket
> node-gyp rebuild

C:\Dev\PV\src\WebServer\node_modules\net-ping\node_modules\raw-socket>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
gyp info it worked if it ends with ok
gyp info using node-gyp@3.0.3
gyp info using node@4.3.1 | win32 | x64
gyp info spawn C:\Python27\python.exe
gyp info spawn args [ 'C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=auto',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Dev\\PV\\src\\WebServer\\node_modules\\net-ping\\node_modules\\raw-socket\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\dylan\\.node-gyp\\4.3.1\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\dylan\\.node-gyp\\4.3.1',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\Dev\\PV\\src\\WebServer\\node_modules\\net-ping\\node_modules\\raw-socket',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\Dev\\PV\\src\\WebServer\\node_modules\\net-ping\\node_modules\\raw-socket\\build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64' ]
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Platforms\x64\PlatformToolsets\v140\Toolset.targets(36,5): error
 MSB8036: The Windows SDK version 8.1 was not found. Install the required version of Windows SDK or change the SDK vers
ion in the project property pages or by right-clicking the solution and selecting "Retarget solution". [C:\Dev\PV\src\W
ebServer\node_modules\net-ping\node_modules\raw-socket\build\raw.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 10.0.10586
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Dev\PV\src\WebServer\node_modules\net-ping\node_modules\raw-socket
gyp ERR! node -v v4.3.1
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
npm info raw-socket@1.4.0 Failed to exec install script
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "net-ping"
npm ERR! node v4.3.1
npm ERR! npm  v2.14.12
npm ERR! code ELIFECYCLE

npm ERR! raw-socket@1.4.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the raw-socket@1.4.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the raw-socket package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls raw-socket
npm ERR! There is likely additional logging output above.
npm info preuninstall raw-socket@1.4.0
npm info uninstall raw-socket@1.4.0
npm info postuninstall raw-socket@1.4.0
npm info preuninstall net-ping@1.2.0
npm info uninstall net-ping@1.2.0
npm info postuninstall net-ping@1.2.0

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Dev\PV\src\WebServer\npm-debug.log

**Comment by stephenwvickers** [comment]
This module uses node-gyp to compile the C++ add-on code.  You need to make sure you have satisfied the node-gyp dependencies:

https://github.com/nodejs/node-gyp

**Comment by Dylan1116** [comment]
Thanks Stephen for looking into this.  I will review the node-gyp

**Comment by jasonLiu001** [comment]
Did it work?

**Comment by debjava** [comment]
> Did it work? I also encounter this problem when i try to install net-ping use `npm install net-ping`

I am also facing the same.
