### ISSUE TITLE
Timestamp reply instead of `sent`, `rcvd`  

### ISSUE THREAD

**Issue by abozhilov** [stephenwvickers/node-net-ping#25]
I've tested the times reported by your lib and they are pretty inaccurate. Unix `ping` uses Timestampt reply packet for response time calculation. 
Would be awesome if you expose those times instead of `sent` and `rcvd` dates. 

e.g

```javascript
session.pingHost ('192.168.0.1', function (error, target, stat) {
    stat.sent       // Originate timestamp
    stat.receive  // Receive timestamp
    stat.transmit // Transmit timestamp
});
``` 

Keep up good work!

**Comment by SterlingButters** [comment]
Was this issue closed because ping accuracy was fixed?
