### ISSUE TITLE
Module Version mismatch, expected 47, got 46

### ISSUE THREAD

**Issue by marcus13345** [stephenwvickers/node-net-ping#28]
![image](https://cloud.githubusercontent.com/assets/6365746/18486243/66f0fe52-79be-11e6-9973-0081087ab8df.png)

I have tried using node v4.5.0 LTS and v6.5.0, but receive the same error in both instances.

**Comment by stephenwvickers** [comment]
Hi,

You have probably changed your version of node without re-compiling all compiled add-on modules.

Try re-installing the module (either delete or maybe try npm uninstall, then npm install again).

Steve
