### ISSUE TITLE
On "DestinationUnreachableError" trace-route request is being tried for "ttl" times, and retries option is ignored

### ISSUE THREAD

**Issue by SameerTi** [stephenwvickers/node-net-ping#33]
when i try to send trace-route request to some unreachable Ip, i get below error as many as configured "ttl" times i.e. default is 30, so i get below trials 30 times, in-spite of the fact that retries option during _createSession_ is configured for 3, so why not try 3 times and give up!?

"hopErrorCode": "DestinationUnreachableError: Destination unreachable (source=blahblah)"
"hopErrorCode": "DestinationUnreachableError: Destination unreachable (source=blahblah)".
"hopErrorCode": "DestinationUnreachableError: Destination unreachable (source=blahblah)".
..
..
"hopErrorCode": "DestinationUnreachableError: Destination unreachable (source=blahblah)".

Primarily why not giving same treatment to "DestinationUnreachableError" as you give to "RequestTimedOutError " ?

**Comment by SameerTi** [comment]
Any updates?

**Comment by stephenwvickers** [comment]
If you want to stop the trace route when you experience this error simply call `close()` on the ping session which will cause the request to finish (and fail).
