### ISSUE TITLE
Can npm install 

### ISSUE THREAD

**Issue by akila16** [stephenwvickers/node-net-ping#34]
gyp ERR! node -v v6.9.4
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm WARN ping-zinger@0.0.0 No repository field.
npm WARN ping-zinger@0.0.0 No license field.
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "net-ping2" "--save"
npm ERR! node v6.9.4
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! raw-socket2@1.2.6 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the raw-socket2@1.2.6 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the raw-socket2 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs raw-socket2
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls raw-socket2
npm ERR! There is likely additional logging output above.
npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\AkilaS\Desktop\WayneF-Projects\PingZinger\PingZinger\npm-debug.log

**Comment by AriesMOo** [comment]
same here :(

**Comment by stephenwvickers** [comment]
HI,

I am not the owner of the raw-socket2 repository, please consult the owner.

While the raw-socket2 module is a fork of my raw-socket module, there are quite a lot of differences between the two.

Steve
