### ISSUE TITLE
session stop getting data when network error occurs.

### ISSUE THREAD

**Issue by RomanBurunkov** [stephenwvickers/node-net-ping#37]
Hi,
I've created such function with closure

```
getPing = function(host, cbSuccess, cbError, reqTimeout){
  var timeout   = (reqTimeout || 2)*1000;
  var session   = netPing.createSession({
    packetSize : 64,
    retries    : 2,
    timeout    : timeout
  });
  session.on('error', function(error){
    logMsg(`ping on error ${host} error: ` + error.toString());
    session.close ();
  });
  return ()=>{
    session.pingHost(host, (error, target, sent, rcvd)=>{
      if(error) {
        logMsg(`ping ${target} error: ` + error.toString());
        cbError(error.toString());
      } else {
        var rtt = rcvd - sent;
        cbSuccess({status:'ok', result:'ok', data:rtt});
      }
      session.close();
    });
  }
}
```

It works, but if I got in log: ping 10.3.4.21 error: RequestTimedOutError: Request timed out,
it will stop calling callbacks until I restart whole project.

Any suggestion how to correct this issue?

Thanks, Roman.

**Comment by stephenwvickers** [comment]
Hi @RomanBurunkov,

It's hard to know without visiblity of `cbSuccess` and `cbError` and their surround code.

I'm guessing that calling the error callback on request timeout and not the success callback halts the flow of your program.

Steve

**Comment by RomanBurunkov** [comment]
Dear @stephenwvickers , thanks for your reply.
You are right, I rewrote my app and at this moment I don't see any errors or stucks.
Sorry for that, but I really checked whole my program several times before adding this issue, and I didn't find a reason for such behaviour.

Thanks, Roman.
