### ISSUE TITLE
App crashing occasionally when try to ping hosts through net-ping.

### ISSUE THREAD

**Issue by RomanBurunkov** [stephenwvickers/node-net-ping#38]
Hi,

I'm getting this errors in logs and then app crashs.

`node: ../deps/uv/src/unix/poll.c:88: uv_poll_stop: Assertion `!(handle->flags & (UV_CLOSING | UV_CLOSED))' failed.`

This happens on Ubuntu server with running node v6.10.0 and net-ping v. 1.2.0

I've found that recently node-uptime project facing with such proplem:
https://groups.google.com/forum/#!topic/nodejs/obdxquewUcE

This usually happens when network has performance issues, such as packet lost and transmit/receive delays. In my app case this could happen 5-7 times for 24 hours.

My ping code looks like this:\

```
getPing = function(session, host, cbSuccess, cbError, reqTimeout){
  if(!session){
    var timeout   = (reqTimeout || 2)*1000;
    var session   = netPing.createSession({
      packetSize : 64,
      retries    : 2,
      timeout    : timeout 
    });
    session.on('error', function(error){
      logMsg(`ping error ${host} error: ` + error.toString());
      session.close ();
    });
  }
  session.pingHost(host, (error, target, sent, rcvd)=>{
    if(error) {
      cbError(error.toString());
    } else {
      var rtt = rcvd - sent;
      cbSuccess({status:'ok', result:'ok', data:rtt});
    }
    session.close();
  });
  return session;
}
```

Thanks, Roman.

**Comment by stephenwvickers** [comment]
What version of raw-socket are you using, can you look at the package.json file under its directory (under node_modules or wherever it is installed) and give me the exact version?

Steve

**Comment by stephenwvickers** [comment]
Also, I don't see what relevance the link you gave has, it seems to related to an issue which is not caused by this module.

**Comment by RomanBurunkov** [comment]
Hello Stephen, the version is:
`├─┬ net-ping@1.2.0
│ └─┬ raw-socket@1.5.1
│   └── nan@2.3.5
`

Sorry, I've posted a wrong link.
Here is another one: https://groups.google.com/forum/#!topic/node-uptime/Ee7IjIXeCow

**Comment by stephenwvickers** [comment]
Hi, is this still an issue for you?

**Comment by RomanBurunkov** [comment]
Hello @stephenwvickers ,

Unfortunately yes. 
It is actual and this one #37 too.

Still have no time to debug this, but planing to look deeper into this.
May be you can advice something how to debug this.

My app crashes or stops getting answers from net-ping if network have any performance problem(timeout, cognitions and etc, I'm using it via internet, not only in local network).

Will update this issue when have something to add.

**Comment by stephenwvickers** [comment]
Hi, have you had time to look into this?

**Comment by santhosh-ktec** [comment]
I predict the issue is here

```
    var session   = netPing.createSession({
      packetSize : 64,
      retries    : 2,
      timeout    : timeout 
    });
```
You should not set var before session here. If you set the session is limited to the scope of if condition  `if(!session)` and `session.pingHost` will throw error still the global scope is not modified (null or undefined).
Hope this will fix ur issue
