### ISSUE TITLE
Ping fails to detect subsequent timeouts after the first time

### ISSUE THREAD

**Issue by spmurrayzzz** [stephenwvickers/node-net-ping#39]
I'm seeing some interesting behavior that I can reproduce reliably, but not sure how to troubleshoot. If I have a script that pings a given host on an interval, once I break the network ACL (intentionally) to force a ping fail, the library does what I expect. And then when I fix the ACL to allow traffic again, the library again does what I expect and ping is successful.

However, once again I try to force a failure by breaking the ACL (disallowing all ICMP traffic to the target host), pings continue to be successful.

Any thoughts?

Here is the script I am running to reproduce:

Node runtime: 6.10
Mac OS X: 10.11.6
raw-socket: 1.5.1
```js
'use strict';

const ping      = require('net-ping');
const session   = ping.createSession({ timeout: 1000 });

setInterval( () => {
  session.pingHost( 'some-public-ipv4', ( err, target ) => {
    if ( err ) {
      console.log('ping fail');
    } else {
      console.log('ping success');
    }
  })
}, 3000 );
```

I am using AWS security group configs to force the success/failure states (by blocking/allowing ICMP traffic)

Here's the script output (annotated for reference)
```
$ node test.js
ping fail
ping fail
ping fail
ping fail
ping fail
# fix ACL
ping success
ping success
ping success
ping success
ping success
# break ACL again 
ping success
ping success
ping success
ping success
ping success
ping success
ping success
```

**Comment by spmurrayzzz** [comment]
Forgot to add that I've demonstrated that this works correctly if I use the native ping binary via `child_process#exec()`. But not a scalable solution long-term.

```js
exec( `ping -c 1 -t 1 ${ host }`, err => {
  if ( err ) {
    console.log('ping fail');
  } else {
    console.log('ping success');
  }
});
```

**Comment by stephenwvickers** [comment]
I'm not familiar with AWS, but I wonder if this relates to a stateful firewall somewhere.

If you stop the process and start it again does it begin to fail as expected?

**Comment by spmurrayzzz** [comment]
If a stateful firewall was the issue, I would expect my second example to exhibit similar behavior.

But yes, if I kick the process it detects the failure successfully.

**Comment by stephenwvickers** [comment]
Could it be something iptables locally, and a per process thing?

**Comment by spmurrayzzz** [comment]
I can test in another location later tonight to see if I can reproduce in another environment.

But so far I've observed this happening locally on my Macbook Pro as well as remotely on Ubuntu Server 14.04

**Comment by stephenwvickers** [comment]
Something like strace would be really useful here, as would a capture using tcpdump.  That way you could now whether it was the OS or net-ping/raw-socket.

**Comment by spmurrayzzz** [comment]
I think your suspicion about some weirdness with a stateful firewall is valid. I can't reproduce this behavior when I actually kill the network stack on the target node (e.g. rebooting, bringing interfaces down, etc).

Ill do some more investigation on this with tcpdump and if I can find any more useful information for you ill add to this issue.

Closing for now. Thanks for your help!
