### ISSUE TITLE
An installation issue

### ISSUE THREAD

**Issue by umutm** [stephenwvickers/node-net-ping#4]
I was just trying to install the module to an AWS instance and couldn't manage to install net-ping.

I have tried with different Nodejs, npm and net-ping versions but all failed similarly.

It always worked fine with AWS and couldn't find out why it failed this time.

Here is the full install log and will be glad to get your thoughts.

ubuntu@ip-161-45-32-241:~$ sudo npm install net-ping@1.1.11
npm http GET https://registry.npmjs.org/net-ping/1.1.11
npm http 200 https://registry.npmjs.org/net-ping/1.1.11
npm http GET https://registry.npmjs.org/net-ping/-/net-ping-1.1.11.tgz
npm http 200 https://registry.npmjs.org/net-ping/-/net-ping-1.1.11.tgz
npm http GET https://registry.npmjs.org/raw-socket
npm http 304 https://registry.npmjs.org/raw-socket
npm http GET https://registry.npmjs.org/nan
npm http 304 https://registry.npmjs.org/nan

> raw-socket@1.4.0 install /home/ubuntu/node_modules/net-ping/node_modules/raw-socket
> node-gyp rebuild

make: Entering directory `/home/ubuntu/node_modules/net-ping/node_modules/raw-socket/build'
  CXX(target) Release/obj.target/raw/src/raw.o
../src/raw.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE raw::SocketWrap::Send(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/raw.cc:662:3: error: ‘Utf8String’ is not a member of ‘v8::String’
   String::Utf8String address (args[3]);
   ^
../src/raw.cc:662:22: error: expected ‘;’ before ‘address’
   String::Utf8String address (args[3]);
                      ^
../src/raw.cc:663:44: error: ‘address’ was not declared in this scope
   struct sockaddr_in6 addr = uv_ip6_addr (*address, 0);
                                            ^
../src/raw.cc:673:3: error: ‘Utf8String’ is not a member of ‘v8::String’
   String::Utf8String address (info[3]);
   ^
../src/raw.cc:673:22: error: expected ‘;’ before ‘address’
   String::Utf8String address (info[3]);
                      ^
../src/raw.cc:674:43: error: ‘address’ was not declared in this scope
   struct sockaddr_in addr = uv_ip4_addr (*address, 0);
                                           ^
make: *** [Release/obj.target/raw/src/raw.o] Error 1
make: Leaving directory `/home/ubuntu/node_modules/net-ping/node_modules/raw-socket/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:809:12)
gyp ERR! System Linux 3.13.0-48-generic
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/ubuntu/node_modules/net-ping/node_modules/raw-socket
gyp ERR! node -v v0.10.29
gyp ERR! node-gyp -v v0.12.1
gyp ERR! not ok
npm ERR! raw-socket@1.4.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the raw-socket@1.4.0 install script.
npm ERR! This is most likely a problem with the raw-socket package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls raw-socket
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 3.13.0-48-generic
npm ERR! command "node" "/usr/local/bin/npm" "install" "net-ping@1.1.11"
npm ERR! cwd /home/ubuntu
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.3.23
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/ubuntu/npm-debug.log
npm ERR! not ok code 0

**Comment by stephenwvickers** [comment]
Hi umutum,

Can you try updating line:

https://github.com/stephenwvickers/node-raw-socket/blob/master/src/raw.cc#L662

To:

Nan::Utf8String address (args[3]);

As well as line:

https://github.com/stephenwvickers/node-raw-socket/blob/master/src/raw.cc#L673

I don't have your version of node/etc. to hand.

Regards

Steve

**Comment by umutm** [comment]
It has now installed with the latest version of Nodejs (without making any changes). Sorry that I had thought it was incompatible with Nodejs v4.

Thanks very much.
