### ISSUE TITLE
All requests timeout during traceroute on Windows 10

### ISSUE THREAD

**Issue by alexanderbanks** [stephenwvickers/node-net-ping#43]
```
C:\Users\alex\Code\Javascript\blizzard-network-debugger\src\api>node index.js
request: addressFamily=1 target=24.105.12.221 id=2 buffer=0800e5c5123800020000000000000000
Feed
Error { [RequestTimedOutError: Request timed out] name: 'RequestTimedOutError', message: 'Request timed out' }
request: addressFamily=1 target=24.105.12.221 id=3 buffer=0800e5c4123800030000000000000000
Feed
Error { [RequestTimedOutError: Request timed out] name: 'RequestTimedOutError', message: 'Request timed out' }
request: addressFamily=1 target=24.105.12.221 id=4 buffer=0800e5c3123800040000000000000000
```

This all happened before I stopped it. Below is the output from just a straight `tracert` command, with the same IP.

```
C:\Windows\system32>tracert 24.105.12.221

Tracing route to 24.105.12.221 over a maximum of 30 hops

  1     5 ms     3 ms     4 ms  192.168.0.1
  2    18 ms    17 ms    17 ms  96.120.60.29
  3    17 ms    27 ms    19 ms  ae-109-rur102.troutdale.or.bverton.comcast.net [162.151.213.157]
  4    28 ms    12 ms    18 ms  ae-52-ar01.troutdale.or.bverton.comcast.net [68.87.216.253]
  5    21 ms    32 ms    18 ms  be-33490-cr01.seattle.wa.ibone.comcast.net [68.86.92.217]
  6    25 ms    28 ms    22 ms  be-10846-pe01.seattle.wa.ibone.comcast.net [68.86.86.90]
```

I'm not sure what else to look for? The same code worked correctly on macOS, but I cannot get it to work on Windows.

The code:

```
var np = require('net-ping')
var sources = []

var session = np.createSession({
    retries: 5,
    _debug: true,
    timeout: 5000
})

session.traceRoute('24.105.12.221', options, feedCallback, doneCallback)

function doneCallback (error, target) {
    if (error) {
        console.log(target + ':', error.toString())
    } else {
        console.log('Trace Route Done')
        console.log('Sources', sources')
    }
}

function feedCallback (error, target, ttl, sent, rcvd) {
    if (error && error.source) {
        sources.push(error.source)
    }
}
```

Thoughts?

**Comment by stephenwvickers** [comment]
As a test can you disable the windows firewall?

I have found that I needed to add an application rule to the windows firewall to allow the return traffic through to the application.

**Comment by stephenwvickers** [comment]
Did disabling Windows firewall make a difference?

**Comment by alexanderbanks** [comment]
It did, everything worked normally then. Sorry for the delay.

I'm not great at Windows. Is this a custom Outbound rule for Node.js? Or a specific port?

**Comment by stephenwvickers** [comment]
Something like this might help you:

```
netsh advfirewall firewall add rule name="Node.js" dir="in" action="allow" program="<path-to-node.exe>"
```

This is untested though :)

**Comment by cark** [comment]
I have the same issue on latest windows 10.
I can do pings with net-ping without issue.
I can tracert using the windows provided tracert.
I instantly receive TimeExceededError errors using net-ping's traceRoute.
The windows firewall and antivirus are disabled. There is no other firewall software installed.
The one thing that's a bit special is that i'm using nwjs instead of node. But I suspect that's not it as I can do normal pings.

**Comment by stephenwvickers** [comment]
@cark Can you please open a separate ticket and  provide a working example failing program?

The original issue in this ticket has been resolved, and I don't want to confuse the two.

Thanks

**Comment by cark** [comment]
I think the behavior I observed is correct. It was only me being uneducated. Sorry again about this.
