### ISSUE TITLE
problem install

### ISSUE THREAD

**Issue by aiaal-n** [stephenwvickers/node-net-ping#44]
At installation displays in a broad gull here such error

123 verbose Windows_NT 10.0.15063
124 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "net-ping"
125 verbose node v8.9.1
126 verbose npm  v5.5.1
127 error code ELIFECYCLE
128 error errno 1
129 error raw-socket@1.5.1 install: `node-gyp rebuild`
129 error Exit status 1
130 error Failed at the raw-socket@1.5.1 install script.
130 error This is probably not a problem with npm. There is likely additional logging output above.
131 verbose exit [ 1, true ]

**Comment by stephenwvickers** [comment]
Can you please confirm versions of:

```
node-gyp -v
node -v
python -V
cl
```

Steve
