### ISSUE TITLE
Windows 7, forbidden error

### ISSUE THREAD

**Issue by d9k** [stephenwvickers/node-net-ping#45]
`var pingSession = ping.createSession();` in my electron application failes with error

`An attempt was made to access a socket in a way forbidden by its access permissions`

at index.js:47:14

```
	this.wrap = new raw.SocketWrap (
			((options && options.protocol)
					? options.protocol
					: 0),
			((options && options.addressFamily)
					? options.addressFamily
					: AddressFamily.IPv4)
		);
```

OS Windows 7 x64

**Comment by stephenwvickers** [comment]
It is likely that you don't have permissions to open raw sockets, or a local application (like Windows firewall or anti-virus) won't permit it.

**Comment by d9k** [comment]
@stephenwvickers, definitely I doesn't have antivirus on this Windows installation.

How can my node js electron application ask user for permission to open raw sockets? Please recommend some node js package for asking user for permission for this  in Windows environment

**Comment by stephenwvickers** [comment]
I have not needed to use such a library so will have to investigate that yourself.
