### ISSUE TITLE
W7x64 VS2015 npm cannot find C:/Program Files (x86)/MSBuild/Microsoft.Cpp/v4.0/V110/Microsoft.Cpp.Default.props

### ISSUE THREAD

**Issue by aniston** [stephenwvickers/node-net-ping#46]
on Windows 7 x64 using npm@3.10.9 and node@v6.11.2 having Visual Studio 2015 Community Edition I ran into the error that npm cound not find C:/Program Files (x86)/MSBuild/Microsoft.Cpp/v4.0/V110/Microsoft.Cpp.Default.props and hence couldn't build.

resolved this by setting the VC target path with
`SET VCTargetsPath=C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140`

Tried again `npm install node-net-ping` and this time it compiled and installed with some minor warnings, checked the example and that worked.

PS: This was my issue related to VS2015 and npm compiling.

**Comment by stephenwvickers** [comment]
I tried a clean installation and it installs fine.  Looks like it could be a localized issue.
