### ISSUE TITLE
Module not found: Can't resolve './build/Release/raw'

### ISSUE THREAD

**Issue by ras24** [stephenwvickers/node-net-ping#50]
Hello,
I want to run the node-net-ping with reactjs and i make it with create-react-app v1.5.1.
 The node-net-ping i install with npm and then i use the code below to make ping test :

`var ping = require ("net-ping");`
`var session = ping.createSession ();`

`session.pingHost ("8.8.8.8", function (error, target) {`
    `if (error)`
      `console.log (target + ": " + error.toString ());`
    `else`
        `console.log (target + ": Alive");`
});`

But the process end with error below :
./node_modules/raw-socket/index.js
Module not found: Can't resolve './build/Release/raw' in '/Users/me/Desktop/nodenetping/node_modules/raw-socket'

I'm using Nodejs v8.9.4 & npm v5.6.0 on macOS Sierra v10.12.6

**Comment by stephenwvickers** [comment]
Are you attempting to use net-ping in the browser?

**Comment by ras24** [comment]
Thank you for your reply.
Yes, i want to show ping result in the browser.
Now i have done with install net-ping in express.js not in react js and send the ping value to react js and it works.

Can i make a request?
I think this module will be good if you can add [mtr (my traceroute)](https://en.wikipedia.org/wiki/MTR_(software))
That's the good ping and traceroute combination.

I hope you can thinking about them.
Thank you very much.

**Comment by stephenwvickers** [comment]
Hi @ras24,

I am not sure what specific functionality you are looking for, but you could probably get quite a lot of functionality via the existing `traceRoute()` function.

You could always implement the functionality and open a patch request :D

Steve

**Comment by YashKharel19** [comment]
Hello, 
Same problem occurred can you help me with issue.
Thanks!

**Comment by stephenwvickers** [comment]
@YashKharel19 This module is not supported to run in the browser.  It requires native code which is compiled during installation which will not work in the browser.
