### ISSUE TITLE
gives error on a IP adress on windows local machine while does not  give error when deployed to bitnami linux server

### ISSUE THREAD

**Issue by BilalAlam173** [stephenwvickers/node-net-ping#52]
I am using net-ping for a small nodejs project to ping a list of IP adresses after regular interval, while testing locally on my windows machine it gives correct result , the dead IP address return error. But as i deployed the application to bitnami linux server net-ping stoped giving me error on the dead IP adresses.Although it gives error when i try to ping an incorrect ip address i.e 1.1.1.10000 etc.
here is the code i am using to ping : 
`function ping(user) {`
  `var options = {`
    `networkProtocol: netPing.NetworkProtocol.IPv4,`
`    packetSize: 4,`
 `   retries: 0,`
   ` sessionId: (process.pid % 65535),`
    `timeout: 1000,`
    `ttl: 128`
`};`
 ` let session = netPing.createSession(options);`
  `session.pingHost(user.ip, function (error, target) {`
   ` console.log(error+'----'+target);`
`// gives null on error even for dead IP address`
 `   if (error) {`
     `......//`
  `  } else {`
`......///`
 `     }`
  `  }`
  `});`

**Comment by stephenwvickers** [comment]
Hi @BilalAlam173,

I would suggest this is a local issue with the bitnami server.

Perhaps a tcpdump and/or strace would help you get to the bottom of the issue.

Steve

**Comment by stephenwvickers** [comment]
Hi @BilalAlam173 

You could try opening just ICMP in the firewall, ICMP echo requests and responses would likely do it.

Steve
