### ISSUE TITLE
TypeError: Cannot read property 'prototype' of undefined

### ISSUE THREAD

**Issue by YashKharel19** [stephenwvickers/node-net-ping#53]
Hello,
I tried using same as the documentation and it gets successfully compiled on terminal while it shows 
TypeError: Cannot read property 'prototype' of undefined
 on the browser side can you help me with the issue.
Thanks!

**Comment by stephenwvickers** [comment]
@YashKharel19 This module is not supported to run in the browser.  It requires native code which is compiled during installation which will not work in the browser.

**Comment by stephenwvickers** [comment]
@YashKharel19 If your application requires ICMP echo request support from the browser, you will likely need to make a request back to a HTTP server where this module could be used.
