### ISSUE TITLE
Is broadcast ping -b a.b.c.255 supported?

### ISSUE THREAD

**Issue by komalpharate** [stephenwvickers/node-net-ping#54]

**Comment by stephenwvickers** [comment]
Unfortunately not easily :(

There are a few issues preventing this.  The first is that SOL_BROADCAST is not exposed as a constant from the raw-socket module.  The second is that the `pingHost()` method exposed by this module will stop at the first ICMP echo response, so you won't get all responses to the request.

The first issue can be worked around simply by using the numerical code for the socket option, i.e. first get the numerical code for `SOL_BROADCAST`:

```
$ grep -R SO_BROADCAST /usr/include/
/usr/include/asm-generic/socket.h:#define SO_BROADCAST  6
```

Then set the socket option on the underlying raw socket used by the ping session:

```
var ping = require("net-ping")
var raw = require("raw-socket")

session = ping.createSession()

session.getSocket().setOption(raw.SocketLevel.SOL_SOCKET, 6, 1)
```

The second issue cannot be easily worked around though, and I can't see a way to do it without a re-work of parts of this module.

Having said that, this module will run many ping requests alongside each other (thousands and thousands), so there's nothing stopping you doing:

```
session = ping.createSession()

for (var i = 1; i < 255; i++) {
   session.pingHost("192.168.1." + i, function(error, target) {
      ...
   })
}
```

This pings the entire subnet for a /24.

**Comment by komalpharate** [comment]
Thank you
