### ISSUE TITLE
Permit users to control the number of permitted hop timeouts for the `traceRoute()` method

### ISSUE THREAD

**Issue by stephenwvickers** [stephenwvickers/node-net-ping#6]
The unexpected behavior is that the traceroute stops after it got three timeouts. I noticed that it is in the documentation, but I had forgot about it. Since many ISP:s block ICMP on some of their equipment, it is common for multiple hosts to not respond. The value of how many timeouts to allow can't be changed since it is hard coded. I want to be able to change that value.

**Comment by alexsotocx** [comment]
Is solved in #10

**Comment by stephenwvickers** [comment]
Implemented 1.2.0 - see the traceRoutes() new ttlOrOptions parameter.  This will be pushed to npm shortly.
