### ISSUE TITLE
npm install net-ping crashing

### ISSUE THREAD

**Issue by MahmoudThePeltist** [stephenwvickers/node-net-ping#74]
When I try to install net-ping to my expressjs project, it crashes during installation:

Node version: v10.16.0
Express: ^4.17.1

`$ npm install net-ping

\> raw-socket@1.7.0 install F:\Projects\Express Js\IPUptimeScanner\node_modules\raw-socket
\> node-gyp rebuild

`F:\Projects\Express Js\IPUptimeScanner\node_modules\raw-socket>if not defined npm_config_node_gyp (node "F:\ProjectApps\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "F:\ProjectApps\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild ) 
gyp ERR! UNCAUGHT EXCEPTION 
gyp ERR! stack Error: spawn F:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\15.0\Bin\MSBuild.exe ENOENT
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
gyp ERR! stack     at onErrorNT (internal/child_process.js:415:16)
gyp ERR! stack     at process._tickCallback (internal/process/next_tick.js:63:19)
gyp ERR! System Windows_NT 10.0.18362
gyp ERR! command "F:\\ProjectApps\\nodejs\\node.exe" "F:\\ProjectApps\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd F:\Projects\Express Js\IPUptimeScanner\node_modules\raw-socket
gyp ERR! node -v v10.16.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! This is a bug in \`node-gyp\`.
gyp ERR! Try to update node-gyp and file an Issue if it does not help:
gyp ERR!     <https://github.com/nodejs/node-gyp/issues>
npm WARN knex@0.21.5 requires a peer of mssql@^6.2.1 but none is installed. You must install peer dependencies yourself.
npm WARN knex@0.21.5 requires a peer of mysql@^2.18.1 but none is installed. You must install peer dependencies yourself.
npm WARN knex@0.21.5 requires a peer of pg@^8.3.0 but none is installed. You must install peer dependencies yourself.
npm WARN knex@0.21.5 requires a peer of sqlite3@^5.0.0 but none is installed. You must install peer dependencies yourself.

npm ERR! code ELIFECYCLE
npm ERR! errno 7
npm ERR! raw-socket@1.7.0 install: \`node-gyp rebuild\`
npm ERR! Exit status 7
npm ERR!
npm ERR! Failed at the raw-socket@1.7.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\PIXEL-PC\AppData\Roaming\npm-cache\_logs\2020-09-10T12_39_04_825Z-debug.log
`

**Comment by MahmoudThePeltist** [comment]
For now I'm using https://www.npmjs.com/package/ping

**Comment by vendornltd** [comment]
@MahmoudThePeltist Do you have node-gyp installed, if so which version?
