### ISSUE TITLE
Allow the ability to ping a hostname

### ISSUE THREAD

**Issue by 3melectronicmonitoring** [stephenwvickers/node-net-ping#8]
I chose this module to ping domain names that are being setup in DNS to detect when they come available but I'm not able to do so because I get an error stating "Invalid IP address".

**Comment by stephenwvickers** [comment]
Hi,

The module only accepts IPv4 or IPv6 addresses, not hostnames.

If you want to ping hostnames, simply use the dns.resolveX() functions to resolve to an IPv4/6 address first.

Steve
